export const ADD_ATTACHMENTS = 'ADD_ATTACHMENTS';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const DELETE_ALL_COMMENTS = 'DELETE_ALL_COMMENTS';
export const DELETE_OWN_COMMENTS = 'DELETE_OWN_COMMENTS';
export const EDIT_ALL_COMMENTS = 'EDIT_ALL_COMMENTS';
export const EDIT_OWN_COMMENTS = 'EDIT_OWN_COMMENTS';
export const PIN_COMMENTS = 'ADD_PIN_COMMENTS';
export const VIEW_COMMENTS = 'VIEW_COMMENTS';