export const GET_COMPARISON_DATA = 'GET_COMPARISON_DATA';
export const GET_COMPARISON_DATA_SUCCESS = 'GET_COMPARISON_DATA_SUCCESS';
export const GET_COMPARISON_DATA_FAILED = 'GET_COMPARISON_DATA_FAILED';


export const GET_TEMPLATE_DATA = 'GET_TEMPLATE_DATA';
export const GET_TEMPLATE_DATA_SUCCESS = 'GET_TEMPLATE_DATA_SUCCESS';
export const GET_TEMPLATE_DATA_FAILED = 'GET_TEMPLATE_DATA_FAILED';

export const SET_COMPARISON_DATA = 'SET_COMPARISON_DATA';
export const CLEAR_COMPARISON_DATA = 'CLEAR_COMPARISON_DATA';

export const SAVE_COMPARISON = 'SAVE_COMPARISON';
export const SAVE_COMPARISON_SUCCESS = 'SAVE_COMPARISON_SUCCESS';
export const SAVE_COMPARISON_FAILED = 'SAVE_COMPARISON_FAILED';

export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';

export const RESET_STATE = 'RESET_STATE';
export const SET_AUTHKEY = 'SET_AUTHKEY';

export const UPDATE_SELECTED_PROPERTIES = 'UPDATE_SELECTED_PROPERTIES';
export const UPDATE_SELECTED_PRODUCTS = 'UPDATE_SELECTED_PRODUCTS';

export const DELETE_COMPARISON = 'DELETE_COMPARISON';
export const DELETE_COMPARISON_FAILED = 'DELETE_COMPARISON_FAILED';
export const DELTE_COMPARISON_SUCCESS = 'DELTE_COMPARISON_SUCCESS';

export const REMOVE_COMPARE_ITEM = 'REMOVE_COMPARE_ITEM';
export const CLEAR_COMPARISON = 'CLEAR_COMPARISON';
export const SAVE_CURRENT_COMPARISON_ID = 'SAVE_CURRENT_COMPARISON_ID';
export const HIGHLIGHT_DIFFERENCES = 'HIGHLIGHT_DIFFERENCES';

export const SET_COMPARE_VIEW_VISIBLE = 'SET_COMPARE_VIEW_VISIBLE';
export const GET_COMPARISON_MODAL_DATA = 'GET_COMPARISON_MODAL_DATA';
export const GET_COMPARISON_MODAL_DATA_SUCCESS = 'GET_COMPARISON_MODAL_DATA_SUCCESS';
export const GET_COMPARISON_MODAL_DATA_FAILED = 'GET_COMPARISON_MODAL_DATA_FAILED';
export const COMPARE_VIEW_CANCEL = 'COMPARE_VIEW_CANCEL';
export const UPDATE_SELECTED_PRODUCTS_FROM_MODAL = 'UPDATE_SELECTED_PRODUCTS_FROM_MODAL';